// The ANDROID half of Focus Nudge's native config — the counterpart of
// withFocusNudgeEntitlements.js, which does the same job for iOS's Family Controls capability.
//
// 🔴 EVERYTHING THIS PLUGIN WRITES IS WHAT GOOGLE REVIEWS.
//
// Play decides that an app "uses the AccessibilityService API" — and therefore owes the sensitive
// permission declaration in PLAY_ACCESSIBILITY_DECLARATION.md plus its multi-week extended review —
// by reading the merged manifest. Not the JS, not the feature flags. That is why the <service> is
// declared here, behind FOCUS_NUDGE_ANDROID in app.config.ts, rather than in the module's own
// AndroidManifest.xml (which would merge into every build unconditionally): the closed test
// (12 testers x 14 days) must be able to ship with no trace of the service, so it is not gated on
// a review it does not need.
//
// Four things, all additive:
//   1. the <service>, with BIND_ACCESSIBILITY_SERVICE and its meta-data pointer;
//   2. res/xml/philoi_focus_nudge_accessibility_config.xml — THE minimal-scope declaration;
//   3. SYSTEM_ALERT_WINDOW, so the nudge can be drawn over the guarded app;
//   4. the <queries> allow-list for the curated packages.
//
// On (4), the decision with a Play consequence: Android has no FamilyActivityPicker, and
// enumerating every installed app requires QUERY_ALL_PACKAGES — a SECOND sensitive-permission
// declaration with its own separate justification and review. Asking about a fixed allow-list of
// named packages requires only <queries> and no declaration at all. So v1 guards a curated list of
// known distracting apps; "pick any app" is a v2 upgrade that buys a second review.
//
// Must be a config plugin, not a hand-edit to android/app/src/main/AndroidManifest.xml: android/ is
// gitignored and regenerated on every prebuild and every EAS build.

const fs = require('fs');
const path = require('path');

const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');

const CATALOG = require('../modules/philoi-focus-nudge/android-guarded-apps.json');

const SERVICE = 'expo.modules.philoifocusnudge.PhiloiFocusNudgeAccessibilityService';
const CONFIG_RESOURCE = 'philoi_focus_nudge_accessibility_config';

/**
 * 🔴 THE HONESTY OF THE PLAY DECLARATION LIVES IN THIS FILE.
 *
 * Every line is a promise PLAY_ACCESSIBILITY_DECLARATION.md makes to Google in prose, and
 * PhiloiFocusNudgeAccessibilityService.kt keeps in code. Read all three together before touching
 * any of them.
 *
 *   accessibilityEventTypes="typeWindowStateChanged"
 *       ONE event type: "an app came to the foreground". Not typeViewTextChanged, not
 *       typeViewFocused, not typeAllMask. This is the entire mechanism, not a subset of it.
 *
 *   canRetrieveWindowContent="false"
 *       The load-bearing one. With this false, getSource(), rootInActiveWindow and every node-tree
 *       API return null — so the claim "never reads your screen" is enforced by the OS rather than
 *       by our good intentions, and a future edit that tries to read content fails at runtime
 *       instead of quietly succeeding.
 *
 *   isAccessibilityTool="false"
 *       Stated explicitly because claiming it falsely is a hard rejection. Focus Nudge is a
 *       digital-wellbeing feature, not an assistive one, and the declaration says so in the same
 *       words.
 *
 *   canPerformGestures / canRequestFilterKeyEvents / canRequestTouchExplorationMode = false
 *       All three are already the default. Written out anyway so the file reads as the declaration
 *       it is: no automation, no input interception, no touch exploration.
 *
 *   notificationTimeout="0"
 *       No coalescing delay. The whole justification for using this API instead of
 *       UsageStatsManager is that the nudge lands before the feed is visible; a notification
 *       timeout would reintroduce exactly the lag we are paying an extended review to avoid.
 *
 * Deliberately ABSENT: android:accessibilityFlags (so: none), and android:packageNames. On the
 * latter — narrowing to the curated list is tempting and looks stricter, but the service also has
 * to notice when the user LEAVES a guarded app, otherwise the overlay (a TYPE_APPLICATION_OVERLAY
 * window) would sit on top of the home screen forever. It still reads nothing but the package name
 * either way, which is precisely what the declaration claims.
 */
const ACCESSIBILITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withFocusNudgeAndroid.js. Edit the plugin, not this file: android/ is
     regenerated on every prebuild and every EAS build. -->
<accessibility-service xmlns:android="http://schemas.android.com/apk/res/android"
    android:accessibilityEventTypes="typeWindowStateChanged"
    android:accessibilityFeedbackType="feedbackGeneric"
    android:notificationTimeout="0"
    android:canRetrieveWindowContent="false"
    android:canPerformGestures="false"
    android:canRequestFilterKeyEvents="false"
    android:canRequestTouchExplorationMode="false"
    android:isAccessibilityTool="false"
    android:summary="@string/philoi_focus_nudge_summary"
    android:description="@string/philoi_focus_nudge_description" />
`;

// The strings the SYSTEM shows on Philoi's row in Settings > Accessibility, and on the confirmation
// dialog Android raises before the service is enabled.
//
// 🔴 These must say the same thing as the store listing and the in-app disclosure. Google's own
// rejection checklist calls a mismatch between the declaration, the listing and what the user is
// told the single biggest cause of rejection, and this is the copy the reviewer sees on-device.
// The wording is lifted from PLAY_ACCESSIBILITY_DECLARATION.md rather than rewritten.
const STRINGS_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withFocusNudgeAndroid.js. Edit the plugin, not this file. -->
<resources>
    <string name="philoi_focus_nudge_label">Philoi Focus Nudge</string>
    <string name="philoi_focus_nudge_summary">Nudges you back to your focus session when you open an app you chose to stay away from.</string>
    <string name="philoi_focus_nudge_description">Philoi uses this to notice the moment you open an app you\\'ve chosen to stay away from during a focus session, so it can show you a quick reminder to lock in instead.\\n\\nIt only checks which app is in front. It never reads your screen, your messages, or anything you type, and nothing leaves your phone.\\n\\nYou pick which apps this applies to, and you can turn it off anytime in Philoi\\'s settings.</string>
</resources>
`;

/** Every package the picker can offer, flattened out of the shared catalog. */
function guardedPackages() {
  return CATALOG.apps.flatMap((app) => app.packages);
}

function withFocusNudgeAndroidManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;

    // ── SYSTEM_ALERT_WINDOW ──
    // Declared here, with the <service>, because the two are useless apart: detection with nothing
    // to draw, or a drawing permission with nothing to trigger it.
    //
    // In practice this is a no-op today — @expo/config-plugins' bare manifest TEMPLATE already
    // carries SYSTEM_ALERT_WINDOW under a "remove whatever you do not need" comment, so every
    // Philoi Android build has shipped with it since long before Focus Nudge existed. Verified
    // against a flag-off prebuild rather than assumed. Kept anyway for two reasons: the day that
    // template drops the line, this feature must not silently lose the ability to draw; and the
    // declaration should be readable HERE, next to the thing that needs it, rather than inherited.
    //
    // No review consequence either way. SYSTEM_ALERT_WINDOW is a special app access the user grants
    // per-app in Settings, not one of Play's declarable sensitive permissions — unlike the
    // <service> below, which is.
    AndroidConfig.Permissions.ensurePermission(cfg.modResults, 'android.permission.SYSTEM_ALERT_WINDOW');

    // ── <queries> ──
    // Merge into the existing block rather than adding a sibling (expo-web-browser and
    // withHealthConnectQueries have already put one there). A second <queries> element is legal but
    // pointlessly messy.
    manifest.queries = manifest.queries || [];
    if (manifest.queries.length === 0) manifest.queries.push({});
    const queries = manifest.queries[0];
    queries.package = queries.package || [];
    for (const packageName of guardedPackages()) {
      const declared = queries.package.some((p) => p?.$?.['android:name'] === packageName);
      if (!declared) queries.package.push({ $: { 'android:name': packageName } });
    }

    // ── the service ──
    const application = manifest.application?.[0];
    if (!application) throw new Error('withFocusNudgeAndroid: no <application> in the manifest.');

    application.service = application.service || [];
    const alreadyDeclared = application.service.some((s) => s?.$?.['android:name'] === SERVICE);
    if (!alreadyDeclared) {
      application.service.push({
        $: {
          'android:name': SERVICE,
          // An accessibility service is bound BY THE SYSTEM, so it must be exported — and the
          // android:permission below is what keeps that from meaning "bindable by anything". Only
          // a caller holding BIND_ACCESSIBILITY_SERVICE (i.e. the system) can reach it.
          'android:exported': 'true',
          'android:permission': 'android.permission.BIND_ACCESSIBILITY_SERVICE',
          'android:label': '@string/philoi_focus_nudge_label',
        },
        'intent-filter': [
          {
            action: [{ $: { 'android:name': 'android.accessibilityservice.AccessibilityService' } }],
          },
        ],
        'meta-data': [
          {
            $: {
              'android:name': 'android.accessibilityservice',
              'android:resource': `@xml/${CONFIG_RESOURCE}`,
            },
          },
        ],
      });
    }

    return cfg;
  });
}

function withFocusNudgeAndroidResources(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const resRoot = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');

      const xmlDir = path.join(resRoot, 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, `${CONFIG_RESOURCE}.xml`), ACCESSIBILITY_CONFIG_XML, 'utf8');

      // Its OWN values file rather than appending to the generated strings.xml — that one is
      // rewritten by expo's own mods and merging into it invites an ordering fight for no gain.
      const valuesDir = path.join(resRoot, 'values');
      fs.mkdirSync(valuesDir, { recursive: true });
      fs.writeFileSync(path.join(valuesDir, 'philoi_focus_nudge_strings.xml'), STRINGS_XML, 'utf8');

      return cfg;
    },
  ]);
}

module.exports = function withFocusNudgeAndroid(config) {
  return withFocusNudgeAndroidResources(withFocusNudgeAndroidManifest(config));
};
