-- 0135 (#150) — a per-type switch actually suppresses its type, and a category outranks the
-- legacy keys it owns.
--
-- ─────────────────────────── two gaps, one file ───────────────────────────
--
-- 1 · notify_event has never had a per-TYPE gate. It checks `master` and `cat_<category>` and
--     nothing finer, so within a category every event is all-or-nothing. The six legacy keys are
--     the only per-type enforcement in the system and they are checked in the OTHER push path
--     (notify_push_raw, 0087), which means a switch that works for a legacy push does nothing for
--     the same-sounding event once it moves onto the event pipeline.
--
--     `type_<event>` closes that: absent = on, so nothing changes for anyone today, and any switch
--     that writes the key is honoured from the moment it does. The mechanism is deliberately
--     generic — a new per-type switch needs no further migration, only a client that writes
--     `type_<the event's type>`.
--
-- 2 · notify_push_raw checks its legacy key WITHOUT checking the category that owns it. That works
--     only because the client happens to write both (categoryPatch), which is a client-side
--     invariant guarding a server-side decision — the exact shape of #144 and #151. An older build,
--     a direct API write, or any future client that forgets, and a user who has switched
--     "Campfires" off still gets campfire pushes. The category is authoritative here now.
--
-- ─────────────────────────── what this deliberately does NOT do ───────────────────────────
--
-- It does not map the six legacy keys onto notify_event's type vocabulary. That mapping is not
-- recoverable from anything in the tree: "Reactions — someone reacts to your lock-in" has no
-- corresponding notify_event type at all, and "Invites and results" would have to decide for
-- itself whether `challenge_cheered` is a result. Guessing it means silently muting notifications
-- people expect, which is worse than the gap it closes, and it is a product call rather than a
-- schema one. The `type_<event>` mechanism above is what lets that decision be expressed the day
-- it is made, without another migration.
--
-- ─────────────────────────── additive-only, mechanically ───────────────────────────
--
-- Both function bodies below were generated by reading the LIVE pg_get_functiondef and inserting
-- whole new lines — no line of either was edited, reordered or retyped. Proven by diffing prosrc
-- before and after: zero removed lines on both. That is the discipline the 0127-reverting-0122 and
-- 0129-dropping-session_complete pair earned.

-- ─────────────────────────── the legacy key's owning category ───────────────────────────

/**
 * Which category owns a legacy per-type key — the server-side twin of CATEGORY_LEGACY_KEYS in
 * lib/notification-prefs.ts, and the only part of that file's mapping that is unambiguous enough
 * to move server-side.
 *
 * Returns the category name WITHOUT the `cat_` prefix, matching notification_category(). An
 * unknown key yields a category nobody has a pref for, whose lookup coalesces to true — so a key
 * this function has not heard of is never a reason to suppress a push.
 */
create or replace function notification_category_for_pref_key(p_key text)
returns text
language sql
immutable
as $ncf$
  select case p_key
    when 'challenges'       then 'challenges'
    when 'campfire_lockins' then 'campfires'
    when 'reactions'        then 'campfires'
    when 'messages'         then 'campfires'
    when 'campfire_cold'    then 'campfires'
    when 'streak_risk'      then 'streak_reminders'
    else '__unmapped__'
  end;
$ncf$;

-- ─────────────────────────── notify_event · the per-type gate ───────────────────────────

CREATE OR REPLACE FUNCTION public.notify_event(p_user_ids uuid[], p_type text, p_title text, p_body text DEFAULT NULL::text, p_actor_id uuid DEFAULT NULL::uuid, p_target_id uuid DEFAULT NULL::uuid, p_route text DEFAULT NULL::text, p_route_params jsonb DEFAULT '{}'::jsonb, p_image_url text DEFAULT NULL::text, p_image_shape text DEFAULT NULL::text, p_payload jsonb DEFAULT '{}'::jsonb)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_category text := notification_category(p_type);
  v_push_default boolean := notification_push_default(p_type);
  v_written int := 0;
  v_push_targets uuid[];
  v_art record;
  v_url text;
  v_shape text;
begin
  if p_user_ids is null or array_length(p_user_ids, 1) is null then
    return 0;
  end if;

  -- An explicitly-passed image always wins; otherwise derive it. This is what lets a caller with
  -- something better than the subject's avatar (a rarity-coloured box) say so, while every other
  -- caller gets the right art for free.
  select * into v_art from notification_leading_art(p_type, p_actor_id, p_target_id);
  v_url := coalesce(p_image_url, v_art.url);
  v_shape := coalesce(p_image_shape, v_art.shape, 'flame');

  insert into notification_events (
    user_id, type, category, actor_id, target_id, title, body,
    route, route_params, image_url, image_shape, payload
  )
  select
    u, p_type, v_category, p_actor_id, p_target_id, p_title, p_body,
    p_route, coalesce(p_route_params, '{}'::jsonb), v_url, v_shape,
    coalesce(p_payload, '{}'::jsonb)
  from unnest(p_user_ids) as u
  where p_actor_id is null or u <> p_actor_id;

  get diagnostics v_written = row_count;

  -- THE ONE ADDED LINE. Everything above and below is 0087's.
  if coalesce(current_setting('philoi.suppress_push', true), 'off') = 'on' then
    return v_written;
  end if;

  select coalesce(array_agg(p.id), '{}')
    into v_push_targets
  from profiles p
  where p.id = any(p_user_ids)
    and (p_actor_id is null or p.id <> p_actor_id)
    and coalesce((p.notification_prefs->>'master')::boolean, true)
    and coalesce((p.notification_prefs->>('cat_' || v_category))::boolean, v_push_default)
    -- #150 · the per-type gate. Inserted ABOVE the quiet-hours line rather than appended to it,
    -- so this is a pure line insertion and the diff removes nothing.
    and coalesce((p.notification_prefs->>('type_' || p_type))::boolean, true)
    and (p_type = 'daily_fire_reminder' or not is_in_quiet_hours(p.notification_prefs));

  if array_length(v_push_targets, 1) is not null then
    perform notify_push_raw(
      v_push_targets,
      p_title,
      coalesce(p_body, ''),
      jsonb_build_object('type', p_type, 'route', p_route, 'params', coalesce(p_route_params, '{}'::jsonb))
        || coalesce(p_payload, '{}'::jsonb),
      'accountability',
      v_url
    );
  end if;

  return v_written;
end;
$function$
;

-- ─────────────────────────── notify_push_raw · the category outranks the key ───────────────────────────

CREATE OR REPLACE FUNCTION public.notify_push_raw(p_user_ids uuid[], p_title text, p_body text, p_data jsonb DEFAULT '{}'::jsonb, p_channel_id text DEFAULT 'accountability'::text, p_image_url text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_messages jsonb;
  v_pref_key text := case p_data->>'type'
    when 'check_in' then 'campfire_lockins'
    when 'reaction' then 'reactions'
    when 'message' then 'messages'
    when 'chat_batch' then 'messages'
    when 'mention' then 'messages'
    when 'lockin_still_here' then 'campfire_cold'
    when 'streak_risk' then 'streak_risk'
    when 'challenge_invite' then 'challenges'
    when 'challenge_completed' then 'challenges'
    else null
  end;
begin
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'to', t.token,
      'title', p_title,
      'body', p_body,
      'data', p_data,
      'sound', 'default',
      'channelId', p_channel_id
    )
    || case when p_image_url is null then '{}'::jsonb
            else jsonb_build_object('richContent', jsonb_build_object('image', p_image_url)) end
  ), '[]'::jsonb)
  into v_messages
  from push_tokens t
  join profiles p on p.id = t.user_id
  where t.user_id = any(p_user_ids)
    and (
      v_pref_key is null
      or (
        coalesce((p.notification_prefs->>'master')::boolean, true)
        and coalesce((p.notification_prefs->>v_pref_key)::boolean, true)
        -- #150 · the category that OWNS this legacy key is authoritative over it. Pure insertion.
        and coalesce(
          (p.notification_prefs->>('cat_' || notification_category_for_pref_key(v_pref_key)))::boolean,
          true)
        and not is_in_quiet_hours(p.notification_prefs)
      )
    );

  if jsonb_array_length(v_messages) = 0 then
    return;
  end if;

  perform net.http_post(
    url := 'https://exp.host/--/api/v2/push/send',
    headers := '{"Content-Type": "application/json", "Accept": "application/json"}'::jsonb,
    body := v_messages
  );
end;
$function$
;

-- create-or-replace preserves privileges, so 0120's revokes on notify_event still stand. Re-asserted
-- anyway: this file's whole claim is that it changes nothing it did not mean to, and a reader should
-- not have to know that rule to believe it. Idempotent either way.
revoke all on function notify_event(uuid[], text, text, text, uuid, uuid, text, jsonb, text, text, jsonb)
  from public, anon, authenticated;
