-- 0219 — the Flame Pass mints two Mythics, and sells none of its season looks. 💰 economy fix
--
-- Two holes, one economy:
--
-- 1. THE PASS FLOODED MYTHICS. Eight Emberfall pass items were Mythic — the L0 flare, L25 banner,
--    L40 particle, L50 halo + sting, L75 card, L100 medal + title. At $8.99 that is a Mythic for
--    ~$1.12, while the Promethean Vault charges 8,000 embers at 12% for one. Nobody opens the vault.
--    Now exactly two, both earned by climbing, both permanent pieces of the profile:
--      • relic-emberfall        L90  — the Emberfall Relic, in the profile showcase     (legendary → MYTHIC)
--      • medal-emberfall-crown  L100 — the Emberfall Crown, the small badge by your name (stays MYTHIC)
--    Seven demoted mythic → legendary: flare-emberfall-ascendant, banner-emberfall-mythic,
--    particle-void-smoke, halo-emberfall-mythic, sfx-emberfall-strike, card-emberfall-mythic,
--    title-forged-in-ember. Ember drip, box weights and the vault price are untouched.
--
--    Rarity lives in four places server-side and they must agree (0213 asserted it):
--      cosmetic_rarity (sale price)    — FULL re-seed from catalog.ts below, because
--                                        scripts/check-cosmetic-rarity.js reads the NEWEST seed as the
--                                        whole table. Regenerate with `--print-seed`.
--      pass_track_rewards.item_rarity  — what claim_pass_level grants at (L25/40/50/75/90/100).
--      box_droppable_items.rarity      — particle-void-smoke is ALSO a vault drop. It moves from the
--                                        mythic pool (5 → 4 items) to legendary (14 → 15). Per-tier
--                                        weights (economy_config.box_odds) do not change.
--      grant_level_zero_unlock         — hands the flare 'mythic' as a literal. Left alone: that value
--                                        only prices the dupe auto-salvage, and the L0 grant is
--                                        once-per-season (pass_claims) for a pass-only item, so the
--                                        dupe path is unreachable. Not worth restating a live
--                                        purchase-path function for.
--
-- 2. PASS LOOKS WERE SELLABLE. salvage_cosmetic fenced source='earned' (0213) but pass grants are
--    source='forge_pass' (0074), so a season's looks could be dumped for embers. Season looks are
--    prestige, not currency — they now refuse like earned items. source='box' and 'paid' stay
--    sellable: vault drops and direct buys are meant to be.
--
-- Restated from live prosrc (md5 7822856d… = 0213's body, verified identical 2026-09-24).
-- Signature unchanged, so installed builds keep working; the only visible change is the refusal.
--
-- NOTE: no explicit begin/commit — the migration runs in its own transaction.

do $guard$
declare
  v_md5 text;
begin
  select md5(p.prosrc) into v_md5 from pg_proc p
  where p.oid = 'public.salvage_cosmetic(text, text)'::regprocedure;
  if v_md5 is distinct from '7822856d3ade49d1302320754f6faafc' then
    raise exception '0219: salvage_cosmetic changed since it was read (md5 %). Re-restate from live prosrc.', v_md5;
  end if;
end;
$guard$;

-- ───────────────────────────── the re-seed ─────────────────────────────
-- Generated by `node scripts/check-cosmetic-rarity.js --print-seed`. Do not hand-edit.

insert into cosmetic_rarity (cosmetic_key, rarity) values
  ('audio-base-hearth-hum', 'common'),
  ('audio-deep-space-sub-bass', 'legendary'),
  ('audio-edm-pulse', 'rare'),
  ('audio-heavy-bonfire-crackle', 'uncommon'),
  ('audio-lofi-lullaby', 'epic'),
  ('audio-midnight-thunder', 'rare'),
  ('audio-monastery-drone', 'epic'),
  ('banner-ashfall', 'legendary'),
  ('banner-ashfall-ridge', 'epic'),
  ('banner-base-hearth', 'common'),
  ('banner-emberfall-mythic', 'legendary'),
  ('banner-emberfall-night', 'epic'),
  ('banner-obsidian-colosseum', 'legendary'),
  ('banner-the-great-forge', 'legendary'),
  ('card-base-hearth', 'common'),
  ('card-brushed-steel', 'uncommon'),
  ('card-carbon-fiber', 'rare'),
  ('card-cracked-magma', 'epic'),
  ('card-emberfall', 'epic'),
  ('card-emberfall-mythic', 'legendary'),
  ('card-emberfall-sovereign', 'mythic'),
  ('card-forged-bronze', 'uncommon'),
  ('card-golden-anvil', 'legendary'),
  ('card-obsidian-mesh', 'rare'),
  ('card-plasma-grid', 'epic'),
  ('flame-base-ember', 'common'),
  ('flame-cosmic-purple', 'legendary'),
  ('flame-electric-cyan', 'rare'),
  ('flame-emberfall', 'epic'),
  ('flame-forge', 'legendary'),
  ('flame-lime-volt', 'rare'),
  ('flame-molten-copper', 'rare'),
  ('flame-neutron-starfire', 'legendary'),
  ('flame-solar-flare', 'epic'),
  ('flame-stormforge', 'mythic'),
  ('flame-toxic-green', 'epic'),
  ('flare-acid-rain', 'legendary'),
  ('flare-asgardian-valor', 'legendary'),
  ('flare-emberfall-ascendant', 'legendary'),
  ('flare-inferno', 'mythic'),
  ('flare-solar', 'epic'),
  ('flare-void-plasma', 'legendary'),
  ('flare-void-purple-aura', 'legendary'),
  ('flare-white-incandescence', 'epic'),
  ('flare-zeus-wrath', 'mythic'),
  ('halo-base-ring', 'common'),
  ('halo-copper-ring', 'uncommon'),
  ('halo-diamond-prism', 'epic'),
  ('halo-ember-halo', 'uncommon'),
  ('halo-emberfall', 'epic'),
  ('halo-emberfall-mythic', 'legendary'),
  ('halo-glowing-amber', 'rare'),
  ('halo-hades', 'mythic'),
  ('halo-inferno-flare', 'legendary'),
  ('medal-campus-sovereign', 'legendary'),
  ('medal-emberfall-centurion', 'legendary'),
  ('medal-emberfall-champion', 'legendary'),
  ('medal-emberfall-crown', 'mythic'),
  ('medal-emberfall-participant', 'common'),
  ('medal-unbroken-season', 'legendary'),
  ('particle-base-spark', 'common'),
  ('particle-ember-swarm', 'epic'),
  ('particle-emberfall-ascendant', 'epic'),
  ('particle-falling-ash', 'epic'),
  ('particle-floating-sparks', 'epic'),
  ('particle-lightning-tendrils', 'legendary'),
  ('particle-solar-flares', 'legendary'),
  ('particle-void-smoke', 'legendary'),
  ('relic-anvil-of-hephaestus', 'legendary'),
  ('relic-athenas-aegis', 'epic'),
  ('relic-atlas-burden', 'mythic'),
  ('relic-crown-of-olympus', 'mythic'),
  ('relic-daedalus-blueprint', 'uncommon'),
  ('relic-emberfall', 'mythic'),
  ('relic-hercules-might', 'uncommon'),
  ('relic-hestias-hearthstone', 'epic'),
  ('relic-icarus-feather', 'legendary'),
  ('relic-pheidippides-sandals', 'rare'),
  ('relic-prometheus-shard', 'mythic'),
  ('relic-socrates-scroll', 'uncommon'),
  ('relic-zeus-bolt', 'mythic'),
  ('sfx-campfire-spark', 'common'),
  ('sfx-ember-settle', 'common'),
  ('sfx-emberfall-strike', 'legendary'),
  ('sfx-heavy-anvil-slam', 'rare'),
  ('sfx-jet-engine-ignition', 'epic'),
  ('sfx-olympian-foghorn', 'legendary'),
  ('sfx-sub-bass-drop', 'rare'),
  ('title-ascended', 'mythic'),
  ('title-ascended-global', 'mythic'),
  ('title-ash-sovereign', 'epic'),
  ('title-ash-walker', 'rare'),
  ('title-ashborne', 'epic'),
  ('title-base-kindling', 'common'),
  ('title-built-different', 'uncommon'),
  ('title-campfire-champion', 'epic'),
  ('title-campfire-finisher', 'rare'),
  ('title-champions-of-academia', 'epic'),
  ('title-cracked', 'rare'),
  ('title-demigod', 'legendary'),
  ('title-dialed-in', 'legendary'),
  ('title-elite-ember', 'epic'),
  ('title-ember-stoker', 'common'),
  ('title-emberfall-ascendant', 'epic'),
  ('title-emberfall-champion', 'mythic'),
  ('title-emberfall-contender', 'rare'),
  ('title-emberfall-elite', 'legendary'),
  ('title-emberfall-initiate', 'uncommon'),
  ('title-final-boss', 'epic'),
  ('title-forged-in-ember', 'legendary'),
  ('title-forged-in-emberfall', 'epic'),
  ('title-iron-forged', 'rare'),
  ('title-keepers-of-the-flame', 'epic'),
  ('title-kept-the-fire', 'rare'),
  ('title-kindled', 'common'),
  ('title-kindled-by-emberfall', 'legendary'),
  ('title-last-flame-standing', 'epic'),
  ('title-locked-in', 'common'),
  ('title-main-character', 'rare'),
  ('title-night-owl', 'common'),
  ('title-ninety-day-siege', 'epic'),
  ('title-pacesetter', 'uncommon'),
  ('title-prometheus-disciples', 'epic'),
  ('title-s1-agni', 'mythic'),
  ('title-s1-built-different', 'legendary'),
  ('title-s1-certified-firestarter', 'rare'),
  ('title-s1-firebreather', 'epic'),
  ('title-s1-helios', 'mythic'),
  ('title-s1-surtur', 'mythic'),
  ('title-s1-the-relentless', 'legendary'),
  ('title-s1-warming-up', 'uncommon'),
  ('title-season-mvp', 'epic'),
  ('title-the-goat', 'epic'),
  ('title-the-relentless', 'epic'),
  ('title-the-undefeated', 'epic'),
  ('title-the-untouchable', 'epic'),
  ('title-titan', 'legendary'),
  ('title-unbroken', 'epic'),
  ('title-villain-arc', 'rare')
on conflict (cosmetic_key) do update set rarity = excluded.rarity;

-- The two copies that must agree with the table above.
update pass_track_rewards p
set item_rarity = cr.rarity
from cosmetic_rarity cr
where cr.cosmetic_key = p.item_key
  and p.item_key in (
    'banner-emberfall-mythic', 'particle-void-smoke', 'halo-emberfall-mythic', 'sfx-emberfall-strike',
    'card-emberfall-mythic', 'title-forged-in-ember', 'relic-emberfall'
  )
  and p.item_rarity is distinct from cr.rarity;

update box_droppable_items d
set rarity = cr.rarity
from cosmetic_rarity cr
where cr.cosmetic_key = d.item_key
  and d.item_key = 'particle-void-smoke'
  and d.rarity is distinct from cr.rarity;

-- ───────────────────────────── the sale ─────────────────────────────

create or replace function salvage_cosmetic(p_key text, p_rarity text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row cosmetics_owned;
  v_rarity text;
  v_payout int;
begin
  if v_user is null then raise exception 'Not signed in'; end if;

  -- p_rarity is VESTIGIAL (0213). It stays in the signature only because installed builds send it;
  -- it is never read. The price is the server's.

  if p_key = any (default_cosmetic_keys()) then
    raise exception 'Starter items are permanent and cannot be sold.';
  end if;

  -- 0212 — kept as a belt to the source rule below.
  if p_key like 'title-campfire-finisher:%' then
    raise exception 'Campfire finisher titles are permanent and cannot be sold.';
  end if;

  -- Locked so a double-tap cannot pay twice for one row.
  select * into v_row from cosmetics_owned
  where user_id = v_user and cosmetic_key = p_key
  for update;

  if v_row.id is null then
    raise exception 'You do not own this item';
  end if;

  -- 0213 — THE fence. Season titles, relics, medals, finisher titles: prestige, not currency.
  if v_row.source = 'earned' then
    raise exception 'Earned items are permanent and cannot be sold.';
  end if;

  -- 0219 — and the season's pass looks with them. A Flame Pass cosmetic is never re-issued; selling
  -- it turned the pass into an ember mint. Box drops and direct buys stay sellable.
  if v_row.source = 'forge_pass' then
    raise exception 'Season pass items are permanent and cannot be sold.';
  end if;

  v_rarity := coalesce(
    v_row.rarity_override,
    (select cr.rarity from cosmetic_rarity cr where cr.cosmetic_key = p_key)
  );
  if v_rarity is null then
    raise exception 'This item cannot be sold right now (no known rarity for %).', p_key;
  end if;

  v_payout := ((select value from economy_config where key = 'salvage_embers') ->> v_rarity)::int;
  if v_payout is null then
    raise exception 'No salvage price for rarity %', v_rarity;
  end if;

  delete from equipped_loadout where user_id = v_user and cosmetic_key = p_key;
  delete from cosmetics_owned where id = v_row.id;
  perform economy_move_embers(v_user, v_payout, 'salvage', null);
  -- `rarity` is new and additive: the rarity actually paid, so a client can stop guessing.
  return jsonb_build_object('embers', v_payout, 'rarity', v_rarity);
end;
$$;

-- ───────────────────────────── assertions ─────────────────────────────

do $assert$
declare
  v_src text;
  v_n int;
  v_keys text;
  v_owner uuid;
  v_key text;
  v_refused text;
  v_before int;
begin
  -- The pass's Mythics are exactly the two capstones, across the whole Emberfall pass set (the L0
  -- flare is granted by literal, not from pass_track_rewards, so the set is checked by key too).
  select string_agg(cosmetic_key, ',' order by cosmetic_key) into v_keys from cosmetic_rarity
  where rarity = 'mythic' and cosmetic_key in (
    'flame-emberfall', 'halo-emberfall', 'card-emberfall', 'title-kindled-by-emberfall',
    'flare-emberfall-ascendant', 'flame-forge', 'title-dialed-in', 'banner-ashfall',
    'banner-emberfall-mythic', 'halo-emberfall-mythic', 'sfx-emberfall-strike', 'card-emberfall-mythic',
    'relic-emberfall', 'medal-emberfall-crown', 'title-s1-the-relentless', 'title-forged-in-ember',
    'particle-void-smoke'
  );
  if v_keys is distinct from 'medal-emberfall-crown,relic-emberfall' then
    raise exception '0219: the pass mythics are [%], expected medal-emberfall-crown,relic-emberfall', v_keys;
  end if;

  select string_agg(item_key, ',' order by item_key) into v_keys from pass_track_rewards
  where item_rarity = 'mythic';
  if v_keys is distinct from 'medal-emberfall-crown,relic-emberfall' then
    raise exception '0219: pass_track_rewards mints mythics [%], expected the two capstones', v_keys;
  end if;

  -- The three rarity copies still agree (0213's invariant, re-checked after moving them).
  if exists (
    select 1 from box_droppable_items d
    left join cosmetic_rarity cr on cr.cosmetic_key = d.item_key
    where cr.rarity is distinct from d.rarity
  ) then
    raise exception '0219: box_droppable_items disagrees with cosmetic_rarity';
  end if;
  if exists (
    select 1 from pass_track_rewards p
    left join cosmetic_rarity cr on cr.cosmetic_key = p.item_key
    where p.item_key is not null and cr.rarity is distinct from p.item_rarity
  ) then
    raise exception '0219: pass_track_rewards disagrees with cosmetic_rarity';
  end if;

  -- The vault still has a mythic pool to roll into.
  select count(*) into v_n from box_droppable_items where rarity = 'mythic';
  if v_n < 1 then raise exception '0219: the vault mythic pool is empty'; end if;

  -- Both fences are in the body.
  select p.prosrc into v_src from pg_proc p where p.oid = 'public.salvage_cosmetic(text, text)'::regprocedure;
  if v_src not like '%v_row.source = ''earned''%' then
    raise exception '0219: salvage_cosmetic lost the earned fence';
  end if;
  if v_src not like '%v_row.source = ''forge_pass''%' then
    raise exception '0219: salvage_cosmetic does not refuse forge_pass items';
  end if;
  if v_src ~ '->>\s*p_rarity' then
    raise exception '0219: salvage_cosmetic prices off p_rarity again';
  end if;

  -- Exercised, not just grepped: sell a real forge_pass row as its owner and expect the refusal.
  -- A refusal raises, so nothing is deleted or paid; the row count is checked either way.
  select user_id, cosmetic_key into v_owner, v_key from cosmetics_owned
  where source = 'forge_pass' order by cosmetic_key limit 1;
  if v_owner is not null then
    select count(*) into v_before from cosmetics_owned where source = 'forge_pass';
    perform set_config('request.jwt.claims', json_build_object('sub', v_owner, 'role', 'authenticated')::text, true);
    begin
      perform salvage_cosmetic(v_key, 'mythic');
      v_refused := null;
    exception when others then
      v_refused := sqlerrm;
    end;
    perform set_config('request.jwt.claims', '', true);
    if v_refused is distinct from 'Season pass items are permanent and cannot be sold.' then
      raise exception '0219: selling forge_pass % was not refused (got: %)', v_key, coalesce(v_refused, 'a sale');
    end if;
    select count(*) into v_n from cosmetics_owned where source = 'forge_pass';
    if v_n <> v_before then raise exception '0219: a refused sale still removed a pass item'; end if;
  end if;

  -- One signature, callable by a signed-in client, not by anon (create or replace keeps grants).
  select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.proname = 'salvage_cosmetic';
  if v_n <> 1 then raise exception '0219: salvage_cosmetic has % overloads', v_n; end if;
  if not has_function_privilege('authenticated', 'public.salvage_cosmetic(text, text)', 'execute') then
    raise exception '0219: authenticated lost execute on salvage_cosmetic';
  end if;
  if has_function_privilege('anon', 'public.salvage_cosmetic(text, text)', 'execute') then
    raise exception '0219: anon can execute salvage_cosmetic';
  end if;
end;
$assert$;
