-- 0223 — nothing ships uncollectable. 🏅
--
-- Agent A follow-up to 0222 (Cosmetic Art Program). Every earned item in the catalog now has a
-- server path that grants it, or is retired on purpose with a comment saying so.
--
-- ─────────────────────────────── WHAT CHANGES ───────────────────────────────
--
-- A · THE VS-UNIS BOARD IS UNREWARDED — DELIBERATELY (Noah, 2026-10-02). close_season_vs_unis keeps
--     writing its season_closures row (so close_season_if_due's ledger is unchanged) and grants
--     NOTHING. Its three collective titles are retired in catalog.ts. Do not "fix" this back.
--
-- B · FOUR ITEMS THAT NOTHING GRANTED, NOW WIRED
--     Hestia's Hearthstone (relic)  — longest_streak ≥ 30, on every completed lock-in (0090's rule,
--                                     back in economy_evaluate_relics after 0119 retired it).
--     Unbroken Season (medal)       — global close: a completed lock-in on every whole local day of
--                                     the season window (season_was_unbroken).
--     The Undefeated (title)        — global close: 3+ settled campfire races against a field of 2+,
--                                     first in every one (season_was_undefeated).
--     Campus Sovereign (medal)      — campus close: #1 on each campus board (season_standings, the
--                                     same board that already pays that person the Sovereign card).
--
-- C · PROMETHEUS STAYS UNEARNABLE IN S1 — DELIBERATELY. has_successful_referral() remains a hard
--     `false`; its comment and the evaluator now say so, so it does not read as a bug.
--
-- D · NO DEAD BANNER KEYS. 0151 retired banner-emberfall and banner-emberfall-elite but left them
--     named in season_titles and in the campus closer's Top-10 band. Repointed to live banners:
--       global rank_2 → banner-obsidian-colosseum   global rank_3 → banner-the-great-forge
--       global p1     → banner-ashfall-ridge        campus Top 10 → banner-the-great-forge
--     and the global closer now grants a banner at the BANNER's rarity, not the title's: a podium
--     title is mythic, and passing that as a dupe banner's price paid a mythic salvage for a
--     legendary banner.
--
-- E · TWO NEW BOX ITEMS (mocks 241/242): Marble of Olympus (card, epic) and Sakura Halo (halo,
--     epic). Into cosmetic_rarity and the epic box pool. Per-tier box weights are unchanged.
--
-- NO BACKFILL (0222's reason: a relic grant spends its one reveal). Hestia arrives on the next
-- completed lock-in; the three close-time items arrive when S1 closes.
--
-- ─────────────────────────────── SAFETY ───────────────────────────────
-- Four functions are restated whole, each md5-pinned to the body this was written against:
--   close_season_vs_unis            0066        close_season_scope              0222
--   grant_season_placement_rewards  0222        economy_evaluate_relics         0222
-- Signatures unchanged; grants carry over (asserted). Every changed body is RUN below inside a
-- rolled-back savepoint, and each grant is checked in both directions.
--
-- NOTE: no explicit begin/commit — the migration runs in its own transaction.

do $guard$
declare
  v_md5 text;
begin
  select md5(replace(p.prosrc, chr(13), '')) into v_md5 from pg_proc p
  where p.oid = 'public.close_season_vs_unis(text)'::regprocedure;
  if v_md5 is distinct from '04fe3336cc536de0fcc768f784a60070' then
    raise exception '0223: close_season_vs_unis is not 0066''s body (md5 %). Re-restate from live prosrc.', v_md5;
  end if;

  select md5(replace(p.prosrc, chr(13), '')) into v_md5 from pg_proc p
  where p.oid = 'public.close_season_scope(text, text, text)'::regprocedure;
  if v_md5 is distinct from '3289c2c4af1380207ee36b2cb2bd8feb' then
    raise exception '0223: close_season_scope is not 0222''s body (md5 %). Was 0222 applied?', v_md5;
  end if;

  select md5(replace(p.prosrc, chr(13), '')) into v_md5 from pg_proc p
  where p.oid = 'public.grant_season_placement_rewards(text, boolean)'::regprocedure;
  if v_md5 is distinct from '9d2269225dec88d8f0f6944101010932' then
    raise exception '0223: grant_season_placement_rewards is not 0222''s body (md5 %). Was 0222 applied?', v_md5;
  end if;

  select md5(replace(p.prosrc, chr(13), '')) into v_md5 from pg_proc p
  where p.oid = 'public.economy_evaluate_relics(uuid)'::regprocedure;
  if v_md5 is distinct from 'f4965714157b370e252d891fbf265666' then
    raise exception '0223: economy_evaluate_relics is not 0222''s body (md5 %). Was 0222 applied?', v_md5;
  end if;
end;
$guard$;

-- ───────────────────────────── the re-seed ─────────────────────────────
-- Generated by `node scripts/check-cosmetic-rarity.js --print-seed`. Do not hand-edit.
-- Against 0222: + card-marble-of-olympus, + halo-sakura. Nothing removed or re-rated.

insert into cosmetic_rarity (cosmetic_key, rarity) values
  ('audio-base-hearth-hum', 'common'),
  ('audio-deep-space-sub-bass', 'legendary'),
  ('audio-edm-pulse', 'rare'),
  ('audio-heavy-bonfire-crackle', 'uncommon'),
  ('audio-lofi-lullaby', 'epic'),
  ('audio-midnight-thunder', 'rare'),
  ('audio-monastery-drone', 'epic'),
  ('banner-ashfall', 'legendary'),
  ('banner-ashfall-ridge', 'epic'),
  ('banner-base-hearth', 'common'),
  ('banner-emberfall-mythic', 'legendary'),
  ('banner-emberfall-night', 'epic'),
  ('banner-obsidian-colosseum', 'legendary'),
  ('banner-the-great-forge', 'legendary'),
  ('card-base-hearth', 'common'),
  ('card-brushed-steel', 'uncommon'),
  ('card-carbon-fiber', 'rare'),
  ('card-cracked-magma', 'epic'),
  ('card-emberfall', 'epic'),
  ('card-emberfall-mythic', 'legendary'),
  ('card-emberfall-sovereign', 'mythic'),
  ('card-forged-bronze', 'uncommon'),
  ('card-golden-anvil', 'legendary'),
  ('card-marble-of-olympus', 'epic'),
  ('card-obsidian-mesh', 'rare'),
  ('card-plasma-grid', 'epic'),
  ('flame-base-ember', 'common'),
  ('flame-cosmic-purple', 'legendary'),
  ('flame-electric-cyan', 'rare'),
  ('flame-emberfall', 'epic'),
  ('flame-forge', 'legendary'),
  ('flame-lime-volt', 'rare'),
  ('flame-molten-copper', 'rare'),
  ('flame-neutron-starfire', 'legendary'),
  ('flame-solar-flare', 'epic'),
  ('flame-stormforge', 'mythic'),
  ('flame-toxic-green', 'epic'),
  ('flare-acid-rain', 'legendary'),
  ('flare-asgardian-valor', 'legendary'),
  ('flare-emberfall-ascendant', 'legendary'),
  ('flare-inferno', 'mythic'),
  ('flare-solar', 'epic'),
  ('flare-void-plasma', 'legendary'),
  ('flare-void-purple-aura', 'legendary'),
  ('flare-white-incandescence', 'epic'),
  ('flare-zeus-wrath', 'mythic'),
  ('halo-base-ring', 'common'),
  ('halo-copper-ring', 'uncommon'),
  ('halo-diamond-prism', 'epic'),
  ('halo-ember-halo', 'uncommon'),
  ('halo-emberfall', 'epic'),
  ('halo-emberfall-mythic', 'legendary'),
  ('halo-glowing-amber', 'rare'),
  ('halo-hades', 'mythic'),
  ('halo-inferno-flare', 'legendary'),
  ('halo-sakura', 'epic'),
  ('medal-campus-sovereign', 'legendary'),
  ('medal-emberfall-centurion', 'legendary'),
  ('medal-emberfall-champion', 'legendary'),
  ('medal-emberfall-crown', 'mythic'),
  ('medal-emberfall-participant', 'common'),
  ('medal-s1-podium-1', 'mythic'),
  ('medal-s1-podium-2', 'legendary'),
  ('medal-s1-podium-3', 'legendary'),
  ('medal-s1-top-1', 'legendary'),
  ('medal-s1-top-10', 'epic'),
  ('medal-s1-top-25', 'common'),
  ('medal-s1-top-5', 'epic'),
  ('medal-s1-top-50', 'common'),
  ('medal-unbroken-season', 'legendary'),
  ('particle-base-spark', 'common'),
  ('particle-ember-swarm', 'epic'),
  ('particle-emberfall-ascendant', 'epic'),
  ('particle-falling-ash', 'epic'),
  ('particle-floating-sparks', 'epic'),
  ('particle-lightning-tendrils', 'legendary'),
  ('particle-solar-flares', 'legendary'),
  ('particle-void-smoke', 'legendary'),
  ('relic-anvil-of-hephaestus', 'legendary'),
  ('relic-athenas-aegis', 'epic'),
  ('relic-atlas-burden', 'mythic'),
  ('relic-crown-of-olympus', 'mythic'),
  ('relic-daedalus-blueprint', 'uncommon'),
  ('relic-emberfall', 'mythic'),
  ('relic-hercules-might', 'uncommon'),
  ('relic-hestias-hearthstone', 'epic'),
  ('relic-icarus-feather', 'legendary'),
  ('relic-pheidippides-sandals', 'rare'),
  ('relic-prometheus-shard', 'mythic'),
  ('relic-socrates-scroll', 'uncommon'),
  ('relic-zeus-bolt', 'mythic'),
  ('sfx-campfire-spark', 'common'),
  ('sfx-ember-settle', 'common'),
  ('sfx-emberfall-strike', 'legendary'),
  ('sfx-heavy-anvil-slam', 'rare'),
  ('sfx-jet-engine-ignition', 'epic'),
  ('sfx-olympian-foghorn', 'legendary'),
  ('sfx-sub-bass-drop', 'rare'),
  ('title-ascended', 'mythic'),
  ('title-ascended-global', 'mythic'),
  ('title-ash-sovereign', 'epic'),
  ('title-ash-walker', 'rare'),
  ('title-ashborne', 'epic'),
  ('title-base-kindling', 'common'),
  ('title-built-different', 'uncommon'),
  ('title-campfire-champion', 'epic'),
  ('title-campfire-finisher', 'rare'),
  ('title-champions-of-academia', 'epic'),
  ('title-cracked', 'rare'),
  ('title-demigod', 'legendary'),
  ('title-dialed-in', 'legendary'),
  ('title-early-bird', 'rare'),
  ('title-elite-ember', 'epic'),
  ('title-ember-stoker', 'common'),
  ('title-emberfall-ascendant', 'epic'),
  ('title-emberfall-champion', 'mythic'),
  ('title-emberfall-contender', 'rare'),
  ('title-emberfall-elite', 'legendary'),
  ('title-emberfall-initiate', 'uncommon'),
  ('title-final-boss', 'epic'),
  ('title-forged-in-ember', 'legendary'),
  ('title-forged-in-emberfall', 'epic'),
  ('title-infernal', 'legendary'),
  ('title-iron-forged', 'rare'),
  ('title-keepers-of-the-flame', 'epic'),
  ('title-kept-the-fire', 'rare'),
  ('title-kindled', 'common'),
  ('title-kindled-by-emberfall', 'legendary'),
  ('title-last-flame-standing', 'epic'),
  ('title-locked-in', 'common'),
  ('title-main-character', 'rare'),
  ('title-night-owl', 'rare'),
  ('title-ninety-day-siege', 'epic'),
  ('title-on-fire', 'epic'),
  ('title-pacesetter', 'uncommon'),
  ('title-prometheus-disciples', 'epic'),
  ('title-s1-agni', 'mythic'),
  ('title-s1-built-different', 'legendary'),
  ('title-s1-certified-firestarter', 'rare'),
  ('title-s1-firebreather', 'epic'),
  ('title-s1-helios', 'mythic'),
  ('title-s1-surtur', 'mythic'),
  ('title-s1-the-relentless', 'legendary'),
  ('title-s1-top-1', 'legendary'),
  ('title-s1-top-10', 'epic'),
  ('title-s1-top-25', 'rare'),
  ('title-s1-top-5', 'epic'),
  ('title-s1-top-50', 'uncommon'),
  ('title-s1-warming-up', 'uncommon'),
  ('title-season-mvp', 'epic'),
  ('title-the-goat', 'epic'),
  ('title-the-relentless', 'epic'),
  ('title-the-undefeated', 'epic'),
  ('title-the-untouchable', 'epic'),
  ('title-titan', 'legendary'),
  ('title-unbroken', 'epic'),
  ('title-villain-arc', 'rare')
on conflict (cosmetic_key) do update set rarity = excluded.rarity;

-- ───────────────────────────── E · the box pool ─────────────────────────────

insert into box_droppable_items (item_key, rarity) values
  ('card-marble-of-olympus', 'epic'),
  ('halo-sakura', 'epic')
on conflict (item_key) do update set rarity = excluded.rarity;

-- ───────────────────────────── D · season_titles banners ─────────────────────────────

update season_titles set banner_asset = 'banner-obsidian-colosseum'
 where season_id = 'S1' and band = 'rank_2' and banner_asset in ('banner-emberfall', 'banner-emberfall-elite');
update season_titles set banner_asset = 'banner-the-great-forge'
 where season_id = 'S1' and band = 'rank_3' and banner_asset in ('banner-emberfall', 'banner-emberfall-elite');
update season_titles set banner_asset = 'banner-ashfall-ridge'
 where season_id = 'S1' and band = 'p1' and banner_asset in ('banner-emberfall', 'banner-emberfall-elite');

-- ───────────────────────────── C · the referral stub ─────────────────────────────

comment on function has_successful_referral(uuid) is
  'DELIBERATELY false for Season 1 (0223, Noah 2026-10-02) — no referral mechanic exists yet, so Prometheus'' Shard (reach Primordial AND bring a friend in) is intentionally unearnable this season. Not a bug. Replace the body when referrals ship; nothing else changes.';

-- ───────────────────────────── A · the Vs-Unis close ─────────────────────────────

create or replace function close_season_vs_unis(p_season text)
returns int
language plpgsql
security definer
set search_path = public
as $$
begin
  -- 0223 — DELIBERATELY UNREWARDED (Noah, 2026-10-02). NOT an oversight; do not restore a grant.
  -- The Vs-Unis board still ranks schools on screen, but its season close pays nothing: its three
  -- collective titles (Prometheus' Disciples, Keepers of the Flame, Champions of Academia) were
  -- cut with mock 249's prune and are retired in catalog.ts. The closure row is still written so
  -- the season ledger records this scope as settled, exactly as before.
  insert into season_closures (season_id, scope, scope_key) values (p_season, 'vs_unis', '')
  on conflict do nothing;
  return 0;
end;
$$;

-- ───────────────────────────── B · the two season-window tests ─────────────────────────────

/**
 * Unbroken Season: a completed lock-in on EVERY whole local day of [p_starts, p_ends). A day the
 * window only partly covers in the user's zone (the opening and closing edges, off by their offset
 * from the season clock) is not required — that would make the medal depend on where you live.
 * A zone Postgres doesn't know falls back to UTC rather than throwing.
 */
create or replace function season_was_unbroken(p_user uuid, p_starts timestamptz, p_ends timestamptz)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tz text;
  v_open timestamp;
  v_first date;
  v_last date;
  v_days int;
begin
  if p_user is null or p_starts is null or p_ends is null or p_ends <= p_starts then return false; end if;

  select nullif(p.timezone, '') into v_tz from profiles p where p.id = p_user;
  begin
    perform now() at time zone coalesce(v_tz, 'UTC');
  exception when others then
    v_tz := null;
  end;
  v_tz := coalesce(v_tz, 'UTC');

  -- First and last WHOLE local days inside the window.
  v_open := p_starts at time zone v_tz;
  v_first := case when v_open = date_trunc('day', v_open) then v_open::date else v_open::date + 1 end;
  v_last := (p_ends at time zone v_tz)::date - 1;
  if v_last < v_first then return false; end if;

  select count(distinct (s.started_at at time zone v_tz)::date) into v_days
  from lock_in_sessions s
  where s.user_id = p_user
    and s.status = 'completed'
    and (s.started_at at time zone v_tz)::date between v_first and v_last;

  return v_days >= (v_last - v_first + 1);
end;
$$;

/**
 * The Undefeated: at least THREE campfire races settled in the window, each against a field of two
 * or more, and first (final_rank = 1, ties included) in every one. A race of one is not a race —
 * solo challenges never count, as wins or as losses. Duels (mode 'h2h') are not campfire races
 * (0212's scope). A race is in the season by when it ENDED.
 */
create or replace function season_was_undefeated(p_user uuid, p_starts timestamptz, p_ends timestamptz)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with races as (
    select p.final_rank,
           (select count(*) from challenge_participants q
             where q.challenge_id = c.id and q.state = 'accepted' and q.final_rank is not null) as field
    from challenge_participants p
    join social_challenges c on c.id = p.challenge_id
    where p.user_id = p_user
      and p.state = 'accepted'
      and p.final_rank is not null
      and c.status = 'completed'
      and c.circle_id is not null
      and c.mode <> 'h2h'
      and coalesce(c.ends_at, c.created_at) >= p_starts
      and coalesce(c.ends_at, c.created_at) < p_ends
  )
  select count(*) >= 3 and count(*) filter (where final_rank > 1) = 0
  from races
  where field >= 2;
$$;

revoke all on function season_was_unbroken(uuid, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function season_was_undefeated(uuid, timestamptz, timestamptz) from public, anon, authenticated;

-- ───────────────────────────── B + D · the global closer ─────────────────────────────
-- 0222's body. Changed: the banner is priced at its own rarity (§D), and the global pass grants
-- Unbroken Season and The Undefeated (§B). Nothing else differs.

create or replace function public.close_season_scope(p_season text, p_scope text, p_key text default null::text)
 returns integer
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_paid int := 0;
  v_is_global boolean := (p_scope = 'global');
  r record;
  v_pct numeric;
  v_band text;
  v_cut text;
  v_title season_titles;
  v_stamp text;
  v_why text;
  v_starts timestamptz;
  v_ends timestamptz;
begin
  insert into season_closures (season_id, scope, scope_key)
  values (p_season, p_scope, coalesce(p_key, ''))
  on conflict do nothing;
  if not found then return 0; end if;

  -- 0201 — the season_settled notification below speaks for the participation badge.
  perform set_config('philoi.quiet_badge', 'on', true);

  -- 0223 — the season window, for the two season-long tests below. Only the season the clock is on
  -- has one; closing any other id simply skips them.
  if season_config() ->> 'id' = p_season then
    v_starts := (season_config() ->> 'starts_at')::timestamptz;
    v_ends := (season_config() ->> 'ends_at')::timestamptz;
  end if;

  for r in
    select p.id as user_id,
           row_number() over (order by universal_score(p.id) desc) as rank,
           count(*) over () as board_size
    from profiles p
    where not p.is_demo and not p.is_disabled
      and (p_scope <> 'uni' or (p.university = p_key and p.university_email_verified))
  loop
    v_pct := r.rank::numeric / greatest(r.board_size, 1);
    perform grant_reward(r.user_id, 'season', 1.0, 90, r.board_size::int, v_pct, true, null);

    -- Everyone who met the floor keeps a dated participation badge (§4b).
    perform economy_grant_badge(r.user_id, 'season-participant-' || p_season, 'Season ' || p_season || ' · took part');

    v_band := season_band(r.rank::int, r.board_size::int);

    -- 0222 — the placement ladder is GLOBAL (Noah, 2026-10-02). A campus board still pays its XP,
    -- badge and notification above and below, and prints its own ladder in 0187's closer.
    if v_is_global and v_band is not null then
      -- The 5% cut lives HERE, not in season_band(): installed builds label bands by name, and a
      -- band they have never seen would render blank. Logged under the band season_band() gave.
      v_cut := case when v_band = 'p10' and v_pct <= 0.05 then 'p5' else v_band end;
      select * into v_title from season_titles st where st.season_id = p_season and st.band = v_cut;

      if v_title.cosmetic_key is not null then
        v_stamp := '🌍 GLOBAL ' ||
          case v_cut
            when 'rank_1' then '#1'
            when 'rank_2' then '#2'
            when 'rank_3' then '#3'
            when 'p1' then '· TOP 1%'
            when 'p5' then '· TOP 5%'
            when 'p10' then '· TOP 10%'
            when 'p25' then '· TOP 25%'
            else '· TOP 50%'
          end || ' · ' || p_season;
        v_why := 'Season ' || p_season || ' · global placement #' || r.rank;

        -- The rarity is the catalog's (cosmetic_rarity), so no override: the finisher ladder's
        -- rarities are explicit, and the old global notch would have mis-priced every one of them.
        perform economy_grant_title(r.user_id, v_title.cosmetic_key, v_why, v_stamp, null);
        perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'title', v_title.cosmetic_key,
                                 v_title.title, v_title.rarity, true, null);

        if v_title.medal_key is not null then
          perform economy_grant_cosmetic(r.user_id, v_title.medal_key, null,
            coalesce((select cr.rarity from cosmetic_rarity cr where cr.cosmetic_key = v_title.medal_key), v_title.rarity),
            'earned', v_why);
          -- "Surtur · Emberfall 1st Finisher" → the medal is "Emberfall 1st Finisher".
          perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'medal', v_title.medal_key,
                                   regexp_replace(v_title.title, '^.* · ', ''),
                                   (select cr.rarity from cosmetic_rarity cr where cr.cosmetic_key = v_title.medal_key),
                                   true, null);
        end if;

        -- The two overlaps mock 249 flagged, both kept.
        if v_cut = 'rank_1' then
          perform economy_grant_title(r.user_id, 'title-ascended', v_why, v_stamp, null);
          perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'title', 'title-ascended',
                                   'Ascended', 'mythic', true, null);
        elsif v_cut = 'p50' and p_season = 'S1' then
          perform economy_grant_title(r.user_id, 'title-s1-warming-up', v_why, v_stamp, null);
          perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'title', 'title-s1-warming-up',
                                   'Warming Up', 'uncommon', true, null);
        end if;

        if v_title.banner_asset is not null then
          -- 0223 — at the BANNER's rarity. The title's (mythic on the podium) priced a dupe banner's
          -- salvage as a mythic.
          perform economy_grant_cosmetic(r.user_id, v_title.banner_asset, 'banner',
            coalesce((select cr.rarity from cosmetic_rarity cr where cr.cosmetic_key = v_title.banner_asset), v_title.rarity),
            'earned', 'Season ' || p_season || ' · ' || v_title.title);
          perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'banner', v_title.banner_asset,
                                   v_title.title || ' Banner',
                                   (select cr.rarity from cosmetic_rarity cr where cr.cosmetic_key = v_title.banner_asset),
                                   true, null);
        end if;
      end if;
    end if;

    -- 0223 — the two season-long achievements. Judged on the GLOBAL pass only, so each person is
    -- considered exactly once (every campus close re-walks the same people).
    if v_is_global and v_starts is not null then
      if season_was_unbroken(r.user_id, v_starts, v_ends) then
        perform economy_grant_cosmetic(r.user_id, 'medal-unbroken-season', null, 'legendary', 'earned',
                                       'Season ' || p_season || ' · a lock-in every single day');
        perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'medal', 'medal-unbroken-season',
                                 'Unbroken Season', 'legendary', true, null);
      end if;
      if season_was_undefeated(r.user_id, v_starts, v_ends) then
        perform economy_grant_title(r.user_id, 'title-the-undefeated',
                                    'Season ' || p_season || ' · every campfire race won', p_season, null);
        perform season_log_grant(p_season, r.user_id, p_scope, v_band, 'title', 'title-the-undefeated',
                                 'The Undefeated', 'epic', true, null);
      end if;
    end if;

    -- 0201 — the season's result, announced once per user per scope.
    perform notify_event(
      array[r.user_id], 'season_settled',
      'Season ' || p_season || case when v_is_global then '' else ' · ' || coalesce(p_key, 'campus') end || ' results are in',
      'You finished #' || r.rank || ' of ' || r.board_size || '. Your rewards are in your inventory.',
      null, null,
      '/inventory', '{}'::jsonb,
      null, null,
      jsonb_build_object('season', p_season, 'scope', p_scope, 'rank', r.rank, 'board_size', r.board_size)
    );

    v_paid := v_paid + 1;
  end loop;

  perform set_config('philoi.quiet_badge', 'off', true);
  return v_paid;
end;
$function$;

-- ───────────────────────────── B + D · the campus closer ─────────────────────────────
-- 0222's body. Changed: #1 also takes the Campus Sovereign medal (§B), and the Top-10 band's
-- banner is a live key (§D). Nothing else differs.

create or replace function grant_season_placement_rewards(p_season text default null, p_dry_run boolean default false)
returns table(university text, ranked integer, granted integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season text := coalesce(p_season, season_config() ->> 'id');
  v_stamp text;
  v_band text;
  v_pct numeric;
  v_granted int := 0;
  r record;
begin
  -- 0187: the same lock close_season_placements takes (re-entrant within one transaction), so a
  -- direct service-role call cannot race the cron either.
  if not p_dry_run then
    perform pg_advisory_xact_lock(hashtext('philoi.season_placements'), hashtext(v_season));
  end if;

  if not p_dry_run and exists (select 1 from season_placement_closures where season_id = v_season) then
    raise notice 'Season % placement rewards already granted; nothing to do.', v_season;
    return query select s.university, count(*)::int, 0
      from season_standings s where s.season_id = v_season group by s.university;
    return;
  end if;

  for r in
    select * from season_standings s where s.season_id = v_season order by s.university, s.rank
  loop
    v_pct := r.rank::numeric / greatest(r.board_size, 1);
    v_band := season_band(r.rank, r.board_size);
    v_stamp := '🎓 ' || upper(r.university) || ' · ' ||
      case
        when r.rank = 1 then '#1'
        when r.rank <= 10 then 'TOP 10'
        when v_pct <= 0.01 then 'TOP 1%'
        when v_pct <= 0.10 then 'TOP 10%'
        else 'TOP 50%'
      end || ' · ' || v_season;

    if not p_dry_run then
      -- ── exclusive placement band ──
      -- 0222: the campus ladder no longer prints a title below #1 (Elite / Ascendant / Contender /
      -- Initiate retired with mock 249's prune — the GLOBAL finisher ladder replaced them). Every
      -- other reward in each band is unchanged.
      if r.rank = 1 then
        perform economy_grant_cosmetic(r.user_id, 'card-emberfall-sovereign', 'card', 'mythic', 'earned', 'Season ' || v_season || ' Champion');
        perform economy_grant_title(r.user_id, 'title-emberfall-champion', 'Season ' || v_season || ' Champion', v_stamp);
        perform economy_grant_cosmetic(r.user_id, 'medal-emberfall-champion', null, 'mythic', 'earned', 'Season ' || v_season || ' Champion');
        perform economy_move_embers(r.user_id, 5000, 'season_reward', null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'card', 'card-emberfall-sovereign', 'Emberfall Sovereign', 'mythic', true, null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'medal', 'medal-emberfall-champion', 'Champion Medal', 'mythic', true, null);
        -- 0223 — the campus #1 also takes Campus Sovereign (mock 246), which nothing granted before.
        perform economy_grant_cosmetic(r.user_id, 'medal-campus-sovereign', null, 'legendary', 'earned', 'Season ' || v_season || ' · #1 on ' || r.university);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'medal', 'medal-campus-sovereign', 'Campus Sovereign', 'legendary', true, null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'embers', 'embers', 'Embers', null, false, 5000);
      elsif r.rank <= 10 then
        -- 0223 — was the Emberfall Elite banner (key retired by 0151). Same slot, same rarity, a live key.
        perform economy_grant_cosmetic(r.user_id, 'banner-the-great-forge', 'banner', 'legendary', 'earned', 'Season ' || v_season || ' Top 10');
        perform economy_move_embers(r.user_id, 2500, 'season_reward', null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'banner', 'banner-the-great-forge', 'The Great Forge', 'legendary', true, null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'embers', 'embers', 'Embers', null, false, 2500);
      elsif v_pct <= 0.01 then
        perform economy_grant_cosmetic(r.user_id, 'particle-emberfall-ascendant', 'particle', 'epic', 'earned', 'Season ' || v_season || ' Top 1%');
        perform economy_move_embers(r.user_id, 1500, 'season_reward', null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'particle', 'particle-emberfall-ascendant', 'Emberfall Ascendant', 'epic', true, null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'embers', 'embers', 'Embers', null, false, 1500);
      elsif v_pct <= 0.10 then
        insert into loot_boxes (user_id, box_key, obtained_via, provenance)
        values (r.user_id, 'furnace', 'season', 'Season ' || v_season || ' Top 10%');
        perform economy_move_embers(r.user_id, 750, 'season_reward', null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'box', 'furnace', 'Furnace Chest', null, false, 1);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'embers', 'embers', 'Embers', null, false, 750);
      elsif v_pct <= 0.50 then
        perform economy_move_embers(r.user_id, 500, 'season_reward', null);
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'embers', 'embers', 'Embers', null, false, 500);
      end if;

      -- ── orthogonal medals ──
      if r.pass_level >= 100 then
        perform economy_grant_cosmetic(r.user_id, 'medal-emberfall-centurion', null, 'legendary', 'earned', 'Season ' || v_season || ' · Level 100');
        perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'medal', 'medal-emberfall-centurion', 'Centurion Medal', 'legendary', true, null);
      end if;
      perform economy_grant_cosmetic(r.user_id, 'medal-emberfall-participant', null, 'common', 'earned', 'Season ' || v_season || ' · took part');
      perform season_log_grant(v_season, r.user_id, 'pass', v_band, 'medal', 'medal-emberfall-participant', 'Participant Medal', 'common', true, null);
    end if;

    v_granted := v_granted + 1;
  end loop;

  if not p_dry_run then
    insert into season_placement_closures (season_id, boards, granted)
    select v_season, count(distinct s.university), v_granted from season_standings s where s.season_id = v_season
    on conflict (season_id) do nothing;
  end if;

  return query select s.university, count(*)::int, v_granted
    from season_standings s where s.season_id = v_season group by s.university;
end;
$$;

-- ───────────────────────────── B + C · the evaluator ─────────────────────────────
-- 0222's body. Changed: Hestia (§B) and the Prometheus comment (§C). Nothing else differs.
-- ⚠️ Still NO `grant execute` (0132).

create or replace function economy_evaluate_relics(p_user uuid)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_granted int := 0;
  v_hours numeric;
  v_tier text;
  v_pos int;
  v_weeks int;
  v_volume numeric;
  v_km numeric;
  v_bench numeric;
  v_squat numeric;
  v_dead numeric;
  v_disc record;
  v_maxed int;
  v_longest int;
  v_streak int;
  v_tz text;
  v_night int;
  v_dawn int;
begin
  if p_user is null then return 0; end if;

  -- ── ANVIL OF HEPHAESTUS · legendary · 500 cumulative hours ──
  -- THE REPAIR, half one. Was lock_in_sessions.(last_confirmed_at - started_at), ~0 per row, which
  -- made a 500-hour relic unreachable by construction rather than by difficulty.
  select coalesce(sum(ci.duration_seconds) / 3600.0, 0) into v_hours
  from check_ins ci
  where ci.user_id = p_user
    and ci.removed_at is null
    and ci.duration_seconds is not null;

  if v_hours >= 500 then
    if economy_grant_relic(p_user, 'relic-anvil-of-hephaestus', 'legendary',
      '500 hours, forged. The work did not fill time — it made you the weapon.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── HESTIA'S HEARTHSTONE · epic · a 30-day streak (0223) ──
  -- Back in the grant path: 0119 retired it, which left the item uncollectable. 0090's rule —
  -- longest_streak, not current, because the relic marks that you HELD the fire for thirty days,
  -- and losing the streak later doesn't un-hold it.
  select longest_streak into v_streak from profiles where id = p_user;
  if coalesce(v_streak, 0) >= 30 then
    if economy_grant_relic(p_user, 'relic-hestias-hearthstone', 'epic',
      'Thirty days without letting the fire go out. The first hearth is yours to keep.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── ICARUS' FEATHER · legendary · ONE lock-in of 5 hours or more (0222, mock 255) ──
  -- Was "reach Hero". The myth is a single flight too close to the sun — one sitting long enough
  -- to scorch the feather, the edge of burnout — not a rank. The longest single check-in, off the
  -- same column the Anvil reads (0168).
  select coalesce(max(ci.duration_seconds), 0) into v_longest
  from check_ins ci
  where ci.user_id = p_user
    and ci.removed_at is null
    and ci.duration_seconds is not null;

  if v_longest >= 5 * 3600 then
    if economy_grant_relic(p_user, 'relic-icarus-feather', 'legendary',
      'Five hours in one sitting — you flew close enough to the sun to scorch the feather.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- The rank, for Zeus and Prometheus below.
  select t.tier into v_tier from rank_tier_for_score(universal_score(p_user)) t limit 1;
  v_pos := array_position(
    array['bronze','silver','gold','platinum','diamond','hero','titan','olympian','immortal','primordial'],
    v_tier);

  -- ── ZEUS' BOLT · mythic · reach DIVINE (0222) ──
  -- Was Primordial. Divine is the `olympian` key — rank-tiers.ts renamed the LABEL for trademark
  -- and kept the key — at position 8; Immortal and Primordial are above it and count too.
  if coalesce(v_pos, 0) >= 8 then
    if economy_grant_relic(p_user, 'relic-zeus-bolt', 'mythic',
      'You reached Divine. The king himself bows toward your greatness.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── ATHENA'S AEGIS · epic · 6 CONSECUTIVE weeks with a session ──
  -- Unchanged from 0119, and deliberately still sourced from lock_in_sessions: this branch counts
  -- WEEKS, asking only whether a session exists in each one and never how long it ran, so the
  -- duration bug never touched it.
  with wk as (
    select distinct date_trunc('week', s.started_at)::date as d
    from lock_in_sessions s
    where s.user_id = p_user and s.status = 'completed'
  ), grouped as (
    select d, d - make_interval(weeks => (row_number() over (order by d))::int) as grp from wk
  )
  select coalesce(max(cnt), 0) into v_weeks
  from (select count(*) as cnt from grouped group by grp) s;

  if v_weeks >= 6 then
    if economy_grant_relic(p_user, 'relic-athenas-aegis', 'epic',
      'Six weeks unbroken, without a gap. Athena guards the standard that is never set down.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── PROMETHEUS' SHARD · mythic · reach PRIMORDIAL and bring a friend in (0222) ──
  -- Was a top-10% season finish + a referral; the summit is now the rank itself.
  -- ⚠ UNEARNABLE IN SEASON 1 — DELIBERATELY (Noah, 2026-10-02). has_successful_referral() is a
  -- hard `false` until a referral mechanic exists. Not a bug: do not soften this condition to make
  -- the relic reachable. When referrals ship, everyone already at Primordial is granted on their
  -- next lock-in, with no backfill.
  if v_tier = 'primordial' and has_successful_referral(p_user) then
    if economy_grant_relic(p_user, 'relic-prometheus-shard', 'mythic',
      'You reached the summit and brought someone into the fire. Mastery that spreads.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── ATLAS' BURDEN · mythic · the 1000 lb club (§4a-3) ── unchanged from 0119.
  select coalesce(max(coalesce(ws.weight, 0)), 0) into v_bench
  from workout_sets ws
  join workout_exercises we on we.id = ws.workout_exercise_id
  join workouts w on w.id = ws.workout_id
  where w.user_id = p_user and we.name ilike '%bench%';

  select coalesce(max(coalesce(ws.weight, 0)), 0) into v_squat
  from workout_sets ws
  join workout_exercises we on we.id = ws.workout_exercise_id
  join workouts w on w.id = ws.workout_id
  where w.user_id = p_user
    and we.name ilike '%squat%'
    and we.name not ilike '%split%'
    and we.name not ilike '%jump%'
    and we.name not ilike '%thrust%';

  select coalesce(max(coalesce(ws.weight, 0)), 0) into v_dead
  from workout_sets ws
  join workout_exercises we on we.id = ws.workout_exercise_id
  join workouts w on w.id = ws.workout_id
  where w.user_id = p_user and (we.name ilike '%deadlift%' or we.name ilike '%rdl%');

  if v_bench + v_squat + v_dead >= 1000 then
    if economy_grant_relic(p_user, 'relic-atlas-burden', 'mythic',
      'A thousand pounds across the three great lifts. Atlas nods in approval.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── DISCIPLINE LADDER · VOLUME (Hercules' Might) ── unchanged from 0119.
  select coalesce(sum(coalesce(ws.weight, 0) * ws.reps), 0) into v_volume
  from workout_sets ws
  join workouts w on w.id = ws.workout_id
  where w.user_id = p_user;

  perform economy_apply_relic_ladder(p_user, 'volume', v_volume);

  -- ── DISCIPLINE LADDER · DISTANCE (Pheidippides' Sandals) ── unchanged from 0119.
  select
    coalesce((select sum(ci.distance_m) from check_ins ci
              where ci.user_id = p_user and ci.removed_at is null), 0)
    + coalesce((select sum(sd.steps) * stride_m_for(p_user) from user_step_days sd
                where sd.user_id = p_user), 0)
  into v_km;
  v_km := v_km / 1000.0;

  perform economy_apply_relic_ladder(p_user, 'distance', v_km);

  -- ── DISCIPLINE LADDERS · HOURS, one per discipline ──
  --
  -- THE REPAIR, half two. Socrates' Scroll (study) · Daedalus' Blueprint (deep work) · Oracle's
  -- Stillness (meditate), each on §4a-2's 10 / 25 / 50 / 100 h ladder.
  --
  -- session_discipline() is 0119's map and is unchanged, so the routing it documents still holds:
  -- `read` folds into study (§4a-2 "Reading counts as study"), `job_applications` is the only
  -- current GoalType that fits deep work, `run` rides Distance instead, and `custom` is
  -- deliberately unmapped rather than credited to a discipline the user did not pick. It is fed
  -- check_ins.goal_type here rather than lock_in_sessions.goal_type — the same denormalised value,
  -- read off the row that actually carries the duration.
  --
  -- ONE grouped pass, not one query per family: this function runs on every check-in insert, and a
  -- query per hours-ladder would be three more scans of the hottest table in the app.
  --
  -- A discipline with no hours gets no row, which costs nothing — get_my_relic_progress and
  -- get_trophy_hall both LEFT JOIN from relic_ladders, so all five ladders still report.
  for v_disc in
    select session_discipline(ci.goal_type) as family,
           sum(ci.duration_seconds) / 3600.0 as hours
    from check_ins ci
    where ci.user_id = p_user
      and ci.removed_at is null
      and ci.duration_seconds is not null
      and session_discipline(ci.goal_type) is not null
    group by 1
  loop
    perform economy_apply_relic_ladder(p_user, v_disc.family, v_disc.hours);
  end loop;

  -- ── CROWN OF OLYMPUS · mythic · top rung of every discipline ladder (§4a-2 capstone) ──
  -- Counted against relic_ladders rather than a literal 5, so a discipline added later joins the
  -- capstone's requirement by INSERT and needs no change here.
  select count(*) into v_maxed
  from relic_progress rp
  join relic_ladders rl on rl.relic_key = rp.relic_key
  where rp.user_id = p_user and rp.tier >= array_length(rl.thresholds, 1);

  if v_maxed >= (select count(*) from relic_ladders) then
    if economy_grant_relic(p_user, 'relic-crown-of-olympus', 'mythic',
      'Master of no single art, but of the discipline beneath all of them. Olympus has a seat for that.')
    then v_granted := v_granted + 1; end if;
  end if;

  -- ── NIGHT OWL · EARLY BIRD · rare titles · 15 lock-ins in a window (0222, mock 249) ──
  -- A matched pair. The hour is the session's START in the user's own zone; the windows are
  -- disjoint (00:00–04:59 and 05:00–08:59) so a 3 AM session counts for exactly one of them.
  -- Only completed sessions of 10+ minutes count: a title is worn in public, and fifteen
  -- thirty-second taps at 1 AM is not what "Night Owl" says about someone.
  --
  -- profiles.timezone, not notification_prefs.timezone (empty on every prod row). A zone Postgres
  -- doesn't recognise must not throw: this runs inside lock_in_sessions_relics, which has no
  -- handler, so an exception here would refuse the lock-in itself. Probe it once, fall back to UTC.
  select nullif(p.timezone, '') into v_tz from profiles p where p.id = p_user;
  begin
    perform now() at time zone coalesce(v_tz, 'UTC');
  exception when others then
    v_tz := null;
  end;

  select count(*) filter (where x.h < 5),
         count(*) filter (where x.h >= 5 and x.h < 9)
    into v_night, v_dawn
  from (
    select extract(hour from s.started_at at time zone coalesce(v_tz, 'UTC')) as h
    from lock_in_sessions s
    join check_ins ci on ci.id = s.ended_check_in_id
    where s.user_id = p_user
      and s.status = 'completed'
      and ci.removed_at is null
      and ci.duration_seconds >= 600
  ) x;

  -- economy_grant_title is one row per key and a no-op when owned — including a Night Owl that
  -- came out of a box before 0222, which keeps its box provenance.
  if v_night >= 15 then
    perform economy_grant_title(p_user, 'title-night-owl', '15 lock-ins after midnight', null, null);
  end if;
  if v_dawn >= 15 then
    perform economy_grant_title(p_user, 'title-early-bird', '15 lock-ins before 9 AM', null, null);
  end if;

  return v_granted;
end;
$$;

-- ───────────────────────────── assertions ─────────────────────────────

do $assert$
declare
  v_n int;
  v_m int;
  v_src text;
  v_uid uuid;
  v_tz text;
  v_day timestamptz;
  v_cfg jsonb := season_config();
  v_marker constant text := '0223-probe-rollback';
  v_err text;
begin
  -- ── the rarity copies still agree ──
  if exists (select 1 from box_droppable_items d left join cosmetic_rarity cr on cr.cosmetic_key = d.item_key
             where cr.rarity is distinct from d.rarity) then
    raise exception '0223: box_droppable_items disagrees with cosmetic_rarity';
  end if;
  if exists (select 1 from pass_track_rewards p left join cosmetic_rarity cr on cr.cosmetic_key = p.item_key
             where p.item_key is not null and cr.rarity is distinct from p.item_rarity) then
    raise exception '0223: pass_track_rewards disagrees with cosmetic_rarity';
  end if;

  -- ── D · no live path names a dead banner ──
  select count(*) into v_n from season_titles
  where banner_asset is not null
    and (banner_asset in ('banner-emberfall', 'banner-emberfall-elite')
         or not exists (select 1 from cosmetic_rarity cr where cr.cosmetic_key = banner_asset));
  if v_n <> 0 then raise exception '0223: % season_titles rows still grant a dead banner', v_n; end if;

  select prosrc into v_src from pg_proc where oid = 'public.grant_season_placement_rewards(text, boolean)'::regprocedure;
  if v_src ~ 'banner-emberfall-elite' then raise exception '0223: the campus closer still grants banner-emberfall-elite'; end if;
  if v_src !~ 'medal-campus-sovereign' then raise exception '0223: the campus closer does not grant Campus Sovereign'; end if;

  -- ── A · Vs-Unis grants nothing and names no cut title ──
  select prosrc into v_src from pg_proc where oid = 'public.close_season_vs_unis(text)'::regprocedure;
  if v_src ~ 'title-(prometheus-disciples|keepers-of-the-flame|champions-of-academia)' or v_src ~ 'economy_grant' then
    raise exception '0223: close_season_vs_unis still grants';
  end if;

  -- ── grants survived create or replace ──
  if has_function_privilege('anon', 'public.close_season_vs_unis(text)', 'execute')
     or has_function_privilege('authenticated', 'public.close_season_vs_unis(text)', 'execute')
     or has_function_privilege('anon', 'public.close_season_scope(text, text, text)', 'execute')
     or has_function_privilege('authenticated', 'public.close_season_scope(text, text, text)', 'execute')
     or has_function_privilege('anon', 'public.grant_season_placement_rewards(text, boolean)', 'execute')
     or has_function_privilege('authenticated', 'public.grant_season_placement_rewards(text, boolean)', 'execute')
     or has_function_privilege('anon', 'public.economy_evaluate_relics(uuid)', 'execute')
     or has_function_privilege('authenticated', 'public.economy_evaluate_relics(uuid)', 'execute')
     or has_function_privilege('anon', 'public.season_was_unbroken(uuid, timestamptz, timestamptz)', 'execute')
     or has_function_privilege('authenticated', 'public.season_was_undefeated(uuid, timestamptz, timestamptz)', 'execute') then
    raise exception '0223: an internal function is client-callable';
  end if;

  -- ══ EXERCISED, NOT GREPPED — each in a savepoint rolled back by the marker ══

  -- B · season_was_unbroken, both directions, on a one-day window. A user with a completed session
  -- must pass on the local day of that session and fail on a day long before Philoi existed.
  select s.user_id, coalesce(nullif(p.timezone, ''), 'UTC'), s.started_at into v_uid, v_tz, v_day
  from lock_in_sessions s join profiles p on p.id = s.user_id
  where s.status = 'completed' and coalesce(nullif(p.timezone, ''), 'UTC') in (select name from pg_timezone_names)
  order by s.started_at desc limit 1;
  if v_uid is not null then
    v_day := (date_trunc('day', v_day at time zone v_tz)) at time zone v_tz;
    if not season_was_unbroken(v_uid, v_day, v_day + interval '1 day') then
      raise exception '0223: season_was_unbroken missed a day with a completed lock-in';
    end if;
    if season_was_unbroken(v_uid, '2001-01-01T00:00:00Z', '2001-01-03T00:00:00Z') then
      raise exception '0223: season_was_unbroken passed days with no lock-in';
    end if;
  end if;

  -- B · season_was_undefeated, both directions, all-time. Anyone who has LOST a field race can
  -- never pass; anyone with 3+ field races and no loss must.
  select count(*) into v_n from (
    select distinct p.user_id from challenge_participants p join social_challenges c on c.id = p.challenge_id
    where p.state = 'accepted' and p.final_rank > 1 and c.status = 'completed' and c.circle_id is not null and c.mode <> 'h2h'
  ) losers where season_was_undefeated(losers.user_id, '-infinity', 'infinity');
  if v_n <> 0 then raise exception '0223: season_was_undefeated passed % players who lost a race', v_n; end if;

  select count(*) into v_n from (
    select p.user_id from challenge_participants p join social_challenges c on c.id = p.challenge_id
    where p.state = 'accepted' and p.final_rank is not null and c.status = 'completed' and c.circle_id is not null
      and c.mode <> 'h2h'
      and (select count(*) from challenge_participants q where q.challenge_id = c.id and q.state = 'accepted' and q.final_rank is not null) >= 2
    group by p.user_id
    having count(*) >= 3 and count(*) filter (where p.final_rank > 1) = 0
  ) unbeaten where not season_was_undefeated(unbeaten.user_id, '-infinity', 'infinity');
  if v_n <> 0 then raise exception '0223: season_was_undefeated failed % players who never lost', v_n; end if;

  -- A · the Vs-Unis close, run: it settles and pays nobody.
  begin
    perform set_config('philoi.suppress_push', 'on', true);
    if close_season_vs_unis('S1') <> 0 then raise exception '0223: close_season_vs_unis reported grants'; end if;
    select count(*) into v_n from cosmetics_owned where acquired_at = now()
      and cosmetic_key in ('title-prometheus-disciples', 'title-keepers-of-the-flame', 'title-champions-of-academia');
    if v_n <> 0 then raise exception '0223: the Vs-Unis close minted % titles', v_n; end if;
    if not exists (select 1 from season_closures where season_id = 'S1' and scope = 'vs_unis') then
      raise exception '0223: the Vs-Unis close no longer records its closure';
    end if;
    raise exception '%', v_marker;
  exception when others then
    get stacked diagnostics v_err = message_text;
    if v_err <> v_marker then raise exception '0223 vs-unis probe: %', v_err; end if;
  end;

  -- B · the global close, run against the live S1 window: Unbroken Season and The Undefeated land
  -- exactly where the tests say, in both directions. (0222's ladder probe already covers the bands.)
  begin
    perform set_config('philoi.suppress_push', 'on', true);
    perform close_season_scope('S1', 'global', null);

    select count(*) into v_n from profiles p
    where not p.is_demo and not p.is_disabled
      and season_was_unbroken(p.id, (v_cfg ->> 'starts_at')::timestamptz, (v_cfg ->> 'ends_at')::timestamptz)
      and not exists (select 1 from cosmetics_owned co where co.user_id = p.id and co.cosmetic_key = 'medal-unbroken-season');
    if v_n <> 0 then raise exception '0223: % unbroken players missed the medal', v_n; end if;
    select count(*) into v_n from cosmetics_owned co
    where co.cosmetic_key = 'medal-unbroken-season' and co.acquired_at = now()
      and not season_was_unbroken(co.user_id, (v_cfg ->> 'starts_at')::timestamptz, (v_cfg ->> 'ends_at')::timestamptz);
    if v_n <> 0 then raise exception '0223: Unbroken Season granted to % players with a dead day', v_n; end if;

    select count(*) into v_n from profiles p
    where not p.is_demo and not p.is_disabled
      and season_was_undefeated(p.id, (v_cfg ->> 'starts_at')::timestamptz, (v_cfg ->> 'ends_at')::timestamptz)
      and not exists (select 1 from cosmetics_owned co where co.user_id = p.id and co.cosmetic_key = 'title-the-undefeated');
    if v_n <> 0 then raise exception '0223: % undefeated players missed the title', v_n; end if;
    select count(*) into v_n from cosmetics_owned co
    where co.cosmetic_key = 'title-the-undefeated' and co.acquired_at = now()
      and not season_was_undefeated(co.user_id, (v_cfg ->> 'starts_at')::timestamptz, (v_cfg ->> 'ends_at')::timestamptz);
    if v_n <> 0 then raise exception '0223: The Undefeated granted to % players who lost', v_n; end if;

    -- D · no banner the close minted is a dead key.
    select count(*) into v_n from cosmetics_owned where acquired_at = now()
      and cosmetic_key in ('banner-emberfall', 'banner-emberfall-elite');
    if v_n <> 0 then raise exception '0223: the global close minted % dead banners', v_n; end if;

    raise exception '%', v_marker;
  exception when others then
    get stacked diagnostics v_err = message_text;
    if v_err <> v_marker then raise exception '0223 global-close probe: %', v_err; end if;
  end;

  -- B · the campus close: exactly the board's #1s take Campus Sovereign, and no dead banner.
  begin
    perform set_config('philoi.suppress_push', 'on', true);
    perform snapshot_season_standings('S1');
    perform grant_season_placement_rewards('S1', false);

    select count(*) into v_n from season_standings s
    where s.season_id = 'S1' and s.rank = 1
      and not exists (select 1 from cosmetics_owned co where co.user_id = s.user_id and co.cosmetic_key = 'medal-campus-sovereign');
    if v_n <> 0 then raise exception '0223: % campus #1s missed Campus Sovereign', v_n; end if;
    select count(*) into v_n from cosmetics_owned co
    where co.cosmetic_key = 'medal-campus-sovereign' and co.acquired_at = now()
      and not exists (select 1 from season_standings s where s.season_id = 'S1' and s.rank = 1 and s.user_id = co.user_id);
    if v_n <> 0 then raise exception '0223: Campus Sovereign granted to % players who were not #1', v_n; end if;
    select count(*) into v_n from cosmetics_owned where acquired_at = now() and cosmetic_key = 'banner-emberfall-elite';
    if v_n <> 0 then raise exception '0223: the campus close minted a dead banner'; end if;

    raise exception '%', v_marker;
  exception when others then
    get stacked diagnostics v_err = message_text;
    if v_err <> v_marker then raise exception '0223 campus-close probe: %', v_err; end if;
  end;

  -- B · Hestia on the evaluator, both directions, for everyone who has completed a session.
  begin
    perform set_config('philoi.suppress_push', 'on', true);
    for v_uid in select distinct s.user_id from lock_in_sessions s where s.status = 'completed' loop
      perform economy_evaluate_relics(v_uid);
    end loop;

    select count(*) into v_n from profiles p
    where p.longest_streak >= 30
      and exists (select 1 from lock_in_sessions s where s.user_id = p.id and s.status = 'completed')
      and not exists (select 1 from cosmetics_owned co where co.user_id = p.id and co.cosmetic_key = 'relic-hestias-hearthstone');
    if v_n <> 0 then raise exception '0223: % players with a 30-day streak missed Hestia', v_n; end if;
    select count(*) into v_m from cosmetics_owned co join profiles p on p.id = co.user_id
    where co.cosmetic_key = 'relic-hestias-hearthstone' and co.acquired_at = now() and coalesce(p.longest_streak, 0) < 30;
    if v_m <> 0 then raise exception '0223: Hestia granted to % players under a 30-day streak', v_m; end if;

    raise exception '%', v_marker;
  exception when others then
    get stacked diagnostics v_err = message_text;
    if v_err <> v_marker then raise exception '0223 evaluator probe: %', v_err; end if;
  end;
end;
$assert$;
